Feature/33 comment query
WebDevStudios/nextjs-wordpress-starter pull request #117
Opened 2021-01-21 20:19 UTC by oddevan

In support of #33 

### Link

Link to the branch preview generated by Vercel.

### Description

What does your feature do? Give some context...

### Screenshot

If possible, add some screenshots of your feature.

### Verification

How will a stakeholder test this?

1.
1.
1.

2021-01-21 22:18 UTC, ravewebdev reviewed
Looks good to me! My only question would be whether we intend to include comments on pages at all, or just posts for now?

2021-01-22 12:47 UTC, gregrickaby requested changes
@oddevan Nicely done. I agree with @ravewebdev on this... can you yank the comment display/query out of pages? I think posts is fine for now.

Thank you!

2021-01-22 17:07 UTC, ravewebdev requested changes
Looks good - just seeing some weird JSDocs on components.

2021-01-22 17:07 UTC, ravewebdev commented on components/blocks/BlockHeadings/BlockHeadings.js
> + * @param {object}    props The component attributes as props.
This should probably be something like:
```
@param {object} props           The component attributes as props.
@param {object} props.props The block attributes props from WordPress.
```

2021-01-22 17:07 UTC, ravewebdev commented on components/blocks/BlockParagraph/BlockParagraph.js
> + * @param {object}    props The component attributes as props.
Same comment issue as above

2021-01-22 18:43 UTC, ravewebdev requested changes

2021-01-22 18:43 UTC, ravewebdev commented on components/blocks/BlockHeadings/BlockHeadings.js
> + * @return {Element}           RichText component with heading content
One last thing - missing a period at the end of the `@return` comment.

2021-01-22 18:43 UTC, ravewebdev commented on components/blocks/BlockParagraph/BlockParagraph.js
> + * @return {Element}           RichText component with paragraph content
Same as above.

2021-01-22 21:31 UTC, ravewebdev approved these changes

2021-01-22 21:32 UTC, gregrickaby approved these changes

2021-01-22 21:32 UTC, merged