Feature/refactor displayblock
WebDevStudios/nextjs-wordpress-starter pull request #878
Opened 2022-01-18 19:54 UTC by itsamoreh

Closes N/A

### Description

* Refactor displayBlock.js, move imports into case statement
* Fully remove LazyBlocks from the frontend

### Screenshot

N/A

### Verification

How will a stakeholder test this?

1. Pull this branch
2. Verify that block still display on the frontend
3. Verify that anything related to LazyBlocks has been fully removed from the frontend

2022-01-20 18:54 UTC, itsamoreh commented on docs/docs/learn/creating-content.md
> +and custom fields!
I removed this! 9e49035

2022-01-20 22:56 UTC, ravewebdev requested changes
Code looks good and everything works!

We should remove the `LzbMediaText` component in `organisms`, though.

2022-02-01 22:21 UTC, ravewebdev approved these changes

2022-02-02 00:54 UTC, gregrickaby approved these changes

2022-02-02 00:54 UTC, merged